#!/usr/bin/env bash
#
# Deploys service in devel mode
#

set -eu
cd "$(dirname "$(realpath "$0")")/.."

cargo build --release

sudo install target/release/hiddenlink /usr/local/sbin/hiddenlink
sudo systemctl restart hiddenlink
sleep 1 && sudo systemctl status hiddenlink

scp target/release/hiddenlink proxy.lan:/var/tmp/hiddenlink
ssh konishchev@proxy.lan '
    set -eu
    sudo install /var/tmp/hiddenlink /usr/local/sbin/hiddenlink
    sudo systemctl restart hiddenlink
    sleep 1 && sudo systemctl status hiddenlink
'