#!/usr/bin/env bash
#
# Deploys service in devel mode
#

set -eu
cd "$(dirname "$(realpath "$0")")/.."

target=x86_64-unknown-linux-musl
cargo build --release --target "$target"

sudo install "target/$target/release/hiddenlink" /usr/local/bin/hiddenlink
sudo systemctl restart hiddenlink
sleep 1 && sudo systemctl status hiddenlink

scp "target/$target/release/hiddenlink" proxy.lan:/var/tmp/hiddenlink
ssh konishchev@proxy.lan '
    set -eu
    sudo install /var/tmp/hiddenlink /usr/local/sbin/hiddenlink
    sudo systemctl restart hiddenlink
    sleep 1 && sudo systemctl status hiddenlink
'
