#!/usr/bin/env bash
#
# Runs service in devel mode
#

set -eu
cd "$(dirname "$(realpath "$0")")/.."

if [ $# -lt 1 ]; then
    echo "Usage: $0 server|client [args]" >&2
    exit 1
fi

name="$1"; shift
args=("$@")

case "$name" in
    server|client)
        ;;

    *)
        echo "Error: Invalid devel role." >&2
        exit 1
        ;;
esac

cargo run -- -vv --config "devel/$name.yaml" "${args[@]}"